### ISSUE TITLE
gcroot etc

### ISSUE THREAD

**Issue by olleharstedt** [OCamlPro/ollvm#15]
Hi! Is it possible to use this lib to generate LLVM IR that uses garbage collection?

**Comment by sagotch** [comment]
It might be possible, but I am not sure about what using a gc implies.

`definition` type has a  [gc field](https://github.com/OCamlPro/ollvm/blob/master/src/ollvm/ollvm_ast.mli#L228).

If `llvm.gcread` and `llvm.gcwrite` calls can be performed as regular calls (and I think it is the case), then there should not be any problem.

The only problem I see is that gateway does not use the gc information of a definition... Adding a `set_gc` call in gateway's `definition` function should fix this issue but I have no time to make sure it is the good fix now.

``` ocaml
let definition : env -> Ollvm.Ast.definition -> env =
  ...
  Llvm.set_gc df.df_gc (lookup_fn env df.df_prototype.dc_name) ;
  ...
```

**Comment by olleharstedt** [comment]
Hi, thanks for your answer. What's the gateway?

**Comment by sagotch** [comment]
[Ollvm_llvmgateway module](https://github.com/OCamlPro/ollvm/blob/master/src/ollvm_llvmgateway/ollvm_llvmgateway.mli) is what you use to go from a Ollvm AST to its llvm representation.

You define a module with `ollvm`, and if you want to use official llvm tools, a call to `Ollvm_llvmgateway.modul` turns it into a value you can use with llvm bindings (i.e. apply predefined optimization passes, use llvm backend to produce machine code, etc...).

You can use Ollvm just as syntaxic sugar for official llvm bindings.
